# Generated by Django 5.1.1 on 2024-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='horario_autorizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de autorização de entrada'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_chegada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada na portaria'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de saída na portaria'),
        ),
    ]
