# Generated by Django 5.1.1 on 2024-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_alter_visitante_horario_autorizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='horario_autorizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horario da autorização de entrada'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_chegada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horario de chegada na portaria'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horario de saida do condominio'),
        ),
    ]
